version: 1
nats:
  path: /eventscale/conf/nats.conf
networks:
  - name: ethereum
    rpc: https://eth.llamarpc.com
    rate_limit:
      per: 1s
      limit: 10
    blocks_proc:
      batch_limit: 10
      interval: 5s
events:
  - name: Transfer
    signature: event Transfer(address indexed from, address indexed to, uint256 value)
    networks:
      ethereum:
        0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48: USDC
        0x6B175474E89094C44Da98b954EedeAC495271d0F: USDT
  - name: Approval
    signature: event Approval(address indexed owner, address indexed spender, uint256 value)
    networks:
      ethereum:
        0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48: USDC